version: 2.1

# Define the jobs we want to run for this project
jobs:
  inicio:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: whoami
  verificacion:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the verificacion job"
  aprovacion_manual:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the aprovacion_manual job"
  desplegue:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the desplegue job"

# Orchestrate our job run sequence
workflows:
  web_server:
    jobs:
      - inicio
      - verificacion:
          requires:
            - inicio
      - aprovacion_manual:
          type: approval
          requires:
            - inicio
            - test
      - desplegue:
          requires:
            - aprovacion_manual
