version: 2.1

# Define the jobs we want to run for this project
jobs:
  desplegue:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: whoami
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the test job"
  hold:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the hold job"
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the deploy job"

# Orchestrate our job run sequence
workflows:
  web_server:
    jobs:
      - desplegue
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
